Bumped alpine version in the Dockerfile to fix build
markdownlint/markdownlint pull request #155
Opened 2017-01-14 14:25 UTC by mkjaer

With the original version I was getting the following error:

`ERROR:  Could not find a valid gem 'mdl' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)`

Bumping Alpine to latest version fixed it.
Also removed an unnecessary apk update.

2019-10-20 00:37 UTC, jaymzh commented
I would imagine the update would be required to get the latest metadata, no?

2019-10-20 00:57 UTC, jaymzh requested changes
I think the update is needed, assuming it works roughly like `apt`

2019-11-09 02:41 UTC, jaymzh commented
@mkjaer ?

2019-11-09 07:02 UTC, mkjaer commented
Update is not required. `--no-cache` will download the metadata without storing it on disk thus saving space.

2019-11-09 07:03 UTC, jaymzh approved these changes

2019-11-09 07:04 UTC, merged

2020-01-09 09:14 UTC, greut commented
@mkjaer where is this image pushed?