change newline delimiter from "\n" to /\R/
markdownlint/markdownlint pull request #238
Opened 2018-09-14 04:38 UTC by tsuburin

Fix of https://github.com/markdownlint/markdownlint/issues/237

2019-10-20 00:33 UTC, jaymzh requested changes

2019-10-20 00:33 UTC, jaymzh commented on lib/mdl/doc.rb
> +      @lines = text.split(/\R/)
```suggestion
      @lines = text.lines
```

2019-10-20 02:01 UTC, jaymzh requested changes
Use ruby's platform-agnostic line-splitting please.

2019-10-20 21:04 UTC, jamesquilty commented
The change to `text.lines` in line 44 caused a large number of MD009, MD022, MD031, and even an MD035, rule violations when I ran with `mdl --git-recurse --style <my style> .` I checked the reported MD009 violations and they were false positive, so I assume that the remaining reported violations are also false positives introduced by this change.

2019-10-20 21:41 UTC, jaymzh approved these changes

2019-10-20 21:41 UTC, jaymzh commented
Yeah, @apjanke pointed that out in the associated bug, it's going to not include the newline characters, and if we strip, that'll miss things. So this is probably the right call.

2019-10-20 21:50 UTC, jaymzh commented
Can you rebase and force-push, that'll kick travis back into shape:

```
git fetch upstream
git rebase upstream/master
git push --force-with-lease origin doc_lines_regex
```

2019-10-20 21:51 UTC, jaymzh commented
Oh nevermind, I managed to kick travis myself

2019-10-20 22:04 UTC, jaymzh commented
OK... you need a rebase and then you have some failing tests. :)

2019-10-23 04:07 UTC, jaymzh requested changes
Requesting changes until tests pass...

2019-11-09 02:35 UTC, jaymzh approved these changes

2019-11-09 02:36 UTC, merged

2019-11-09 02:36 UTC, jaymzh commented
Thanks!