Updated doc.rb to have a raw_text attribute reader
markdownlint/markdownlint pull request #349
Opened 2020-09-01 23:28 UTC by androidseb

## Description
Adding a raw_text attr_reader to allow for custom rules to access the raw text of the processed MD file.
Initial closed PR (git commits mess problems):
https://github.com/markdownlint/markdownlint/pull/347

## Related Issues
https://github.com/markdownlint/markdownlint/issues/346

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [X] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [X] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [X] Feature branch is up-to-date with `master`, if not - rebase it
- [ ] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [X] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

2020-09-01 23:29 UTC, androidseb commented
Following up to the PR I closed (I had issues retro-actively fixing my git commits):
https://github.com/markdownlint/markdownlint/pull/347

2020-09-01 23:31 UTC, jaymzh commented
My comment from the other PR:

You're looking at the wrong line. That's the frontmatter regex. Look
https://github.com/markdownlint/markdownlint/pull/347/files#diff-80a3739acc5167507a406303be4d6473R38
it's:
```
@lines = text.split(/\R/)
```
That's it. It's just splitting on lines, that's all.

2020-09-01 23:36 UTC, androidseb commented
I see. I need to look into this a little more, maybe the constructor text is already stripped?
In that case I guess the change I'm proposing would change nothing.
I'll play around with the gem files directly tomorrow to experiment a bit, and I'll post back here this week, thanks!

2020-09-01 23:39 UTC, jaymzh commented
Yaeh if you re-join on `\R` it should get you the exact text you want. Not that I mind making @text available... the only downside is more stuff in memory (we throw it away at this point), but that's doable if we have a reason

2020-09-01 23:41 UTC, DavidAnson commented
I don't use Ruby, but it looks like you may want to pass a negative `limit` parameter to `split` in order to preserve the trailing blank line.

https://ruby-doc.org/core-2.4.0/String.html#method-i-split

2020-09-01 23:42 UTC, jaymzh commented
in our case we actually don't want the newlines... i

2020-09-01 23:47 UTC, DavidAnson commented
@androidseb Seems to want to know if there is a trailing line break or not. By default, `split` seems to trim an empty last item, so you can't tell. What I suggest should preserve it and allow distinguishing the two cases - see the last example at the link I sent.

2020-09-01 23:50 UTC, jaymzh commented
That's not the impression I get. The impression I get is that he wants the newlines in between each line in the array. Which is doable with a join. The negative limit option only adds ones blank element to the array:

```
irb(main):002:0> x = "stuff\nstuff\nstuff\n"
irb(main):003:0> x.split(nil, -1)
=> ["stuff", "stuff", "stuff", ""]
```

If that's what the OP wants, that's doable, but I dont' think that's what the user is after.

2020-09-01 23:58 UTC, androidseb commented
Actually, yes, that's exactly what I'm after, I would like to have that last blank element!

I'm trying to build a rule to detect if the last line of a file is empty, which right now is not possible with the current split policy.
I figured it was something like this, my motivation for creating a new attribute in memory versus changing the split is that:

1. Changing the way the split is currently done might break some existing rules and have un-intended side effects
2. If some other use case like mine comes up in the future for other creators of rules, they have access to the raw source text in case they need it

2020-09-02 00:01 UTC, jaymzh commented
Aha! OK, I didn't understand that! Thanks @DavidAnson  for jumping in!

In that case that's probably the right change (adding a limit=-1). It doesn't affect any of the other lines, just adds another one. We have copious tests around the various rules, so things that break should be easy to spot and fix, worth giving it a shot.

Plus this will your rule easy: `if lines[-1].empty?`

2020-09-02 00:04 UTC, androidseb commented
Yes indeed, if you make that change, I'll be able to use this code :+1:

2020-09-02 00:04 UTC, jaymzh commented
I was suggesting you change this PR to make that change and see how it goes :)

2020-09-02 00:10 UTC, androidseb commented
I've made the code change, but I haven't tested at all.
Are automated tests enough for that small change?

2020-09-02 00:37 UTC, jaymzh requested changes
Yeah, we have copious tests, I feel pretty confident they'd catch breakages here.

But just for shits and giggles, I'd run this locally on a few MD files and ensure it behaves as expected. Mind doing that?

That plus the adding the comment I reference above, and I'm happy to approve this.

Thanks!

2020-09-02 00:37 UTC, jaymzh commented on lib/mdl/doc.rb
> +      @lines = text.split(/\R/, -1)
can we add a comment here?
```suggestion
      # the -1 is to cause split to preserve an extra entry in the array so we can
      # tell if there's a final newline in the file or not.
      @lines = text.split(/\R/, -1)
```

2020-09-02 12:26 UTC, androidseb commented
I have added the comment you requested.
I'll test this out locally and let you know soon.

2020-09-02 12:59 UTC, androidseb commented
I patched the gem file directly to test this out quickly.
Without the change, it was not working, but I can confirm it works perfectly with that change.
This custom rule now works as expected with this change:
```ruby
rule "RE002", "File should end with an empty line" do
  aliases 'file-should-end-with-empty-line'
  check do |doc|
    # check code goes here
    # return a list of line numbers that break the rule, or an empty list
    # (or nil) if there are no problems.

    error_lines = []
    if !doc.lines[-1].empty?
      error_lines.push(0)
    end
    error_lines
  end
end
```

2020-09-02 16:33 UTC, jaymzh approved these changes

2020-09-02 16:34 UTC, jaymzh commented
Awesome, thanks!

BTW I think that's a super good rule. If you want to make a PR to submit that rule, I'll accept that too.

2020-09-02 16:35 UTC, merged

2020-09-02 16:49 UTC, androidseb commented
Thanks for merging this in!
About adding this rule to markdownlint, that's a good idea, I'll work on a PR later this week :+1: