Add support for the XDG Base Directory Specification
markdownlint/markdownlint pull request #377
Opened 2021-04-06 20:03 UTC by mohkale

## Description
Adds an extra lookup path for the mdl config file to XDG_CONFIG_HOME.
In the interest of consistency and backwards compatibility the XDG
path check has a lower precedence than the ~/.mdlrc path.

## Related Issues
Closes #376

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [X] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [X] Feature branch is up-to-date with `master`, if not - rebase it
- [ ] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [X] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

2021-04-06 20:03 UTC, mohkale commented
Will add tests soon.

2022-05-17 23:28 UTC, jaymzh requested changes

2022-05-17 23:28 UTC, jaymzh commented on lib/mdl/cli.rb
> +          File.expand_path("~/#{CONFIG_DOT_FILE}"),
shouldn't we prioritize XDG over legacy?

2022-05-17 23:28 UTC, jaymzh commented on lib/mdl/cli.rb
> +          File.expand_path("~/#{CONFIG_DOT_FILE}"),
also, docs should be updated to reflect this, please

2022-09-30 16:33 UTC, jaymzh commented
Ping @mohkale

2023-09-06 21:04 UTC, jaymzh commented
Ping @mohkale

2023-10-04 23:30 UTC, jaymzh commented
Closing without merge.

2023-10-04 23:30 UTC, closed without merging