Add MD010 option to allow hard tabs in code blocks
markdownlint/markdownlint pull request #396
Opened 2021-11-23 08:27 UTC by ajaust

## Description

This PR adds an option to ignore hard tabs (MD010) in code blocks. This is useful, as hard tabs might be part of the code inside these blocks (e.g., Makefiles).

This PR changes the following:

- The implementation of MD010 has changed and it is similar to the implementation of MD013. First, the lines of code blocks are identified. Then all lines with hard tabs are identified and finally lines that are within code blocks are removed from the list of lines with hard tabs.
- The parameter to check for or ignore hard tabs in code blocks is called `code_blocks`. Its default value is `true` which means code blocks should be checked. By have the default value set to `true` the new parameter does not affect the default behavior of mdl.
- I added the new parameter to the documentation and made a note in the changelog.
- I tried to set up a test (`files hard_tabs_code_blocks.md` and `hard_tabs_code_blocks_style.rb`).

## Open questions/problems:

- Should we rename the parameter to `ignore_code_blocks` as suggested in #395? I would prefer `ignore_code_blocks` a lot since it is more meaningful, but MD013 already uses the name `code_blocks` for a parameter with basically the same meaning (ignore rule for code blocks). So maybe the naming of the parameter(s) should be part of a new issue? Changing the parameter name of rule MD013 could break existing configurations.
- I added a test (files hard_tabs_code_blocks.md and hard_tabs_code_blocks_style.rb). I was able to make work for the most parts. However, it flags an error regarding rule MD040 (Fenced code blocks should have a language specified) in line 5. It seems that mdl identifies lines starting with a hard tab as code block. Is this intended and expected?
  - Due to the unclear test situation I did not mark the "Added tests" box below.
- I have no experience with Ruby so any hint or critical feedback is welcome. I did my best to follow the style and ideas of already implemented features and tests.
- I am not sure whether I am allowed to make the "good commit messages" box. :wink: 

## Related Issues

This PR is related to #395 

This PR is related to rule MD010

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [ ] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [ ] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

2021-11-23 18:13 UTC, jaymzh requested changes
Your test is failing because that line is triggering another rule (MD40):
```
 Expected: {"MD010"=>[5, 7]}
  Actual: {"MD010"=>[7], "MD040"=>[5]}
```

Try adding a language to that code block.

2021-11-23 18:13 UTC, jaymzh commented on CHANGELOG.md
> +* Added option `:code_blocks` to rule MD010. If set to false, hard tabs in code blocks
```suggestion
* Added option `:ignore_code_blocks` to rule MD010. If set to false, hard tabs in code blocks
```

2021-11-23 18:13 UTC, jaymzh commented on docs/RULES.md
> +Parameters: code_blocks (boolean; default true)
```suggestion
Parameters: ignore_code_blocks (boolean; default false)
```

2021-11-23 18:13 UTC, jaymzh commented on docs/RULES.md
> +`code_blocks` parameter to false.
```suggestion
`ignore_code_blocks` parameter to true.
```

2021-11-23 18:13 UTC, jaymzh commented on lib/mdl/rules.rb
> +  params :code_blocks => true
```suggestion
  params :ignore_code_blocks => false
```

2021-11-23 18:13 UTC, jaymzh commented on lib/mdl/rules.rb
> +    hard_tab_lines -= codeblock_lines unless params[:code_blocks]
```suggestion
    hard_tab_lines -= codeblock_lines if params[:ignore_code_blocks]
```

2021-11-23 18:13 UTC, jaymzh commented on test/rule_tests/hard_tabs_code_blocks_style.rb
> +rule 'MD010', :code_blocks => false
```suggestion
rule 'MD010', :ignore_code_blocks => true
```

2021-11-23 18:14 UTC, jaymzh commented
As to the naming, yeah I'd rather use better naming going forward.

2021-11-23 18:18 UTC, ajaust commented
One (stupid) question. I see that the test is failing due to MD040. However, from my understanding this line (5) is illegal per se as it starts with a hard tab. Nevertheless, mdl interprets line 5 as a code block and then complains about the missing language specifier (which I understand). 

Is it correct that a line starting with a hard tab (line 5) is interprested as code block? I though code blocks start with four space character or by using fences.

2021-11-23 18:18 UTC, ajaust commented
And thanks for the quick review. I will try to include the changes quickly.

2021-11-23 18:21 UTC, jaymzh commented
I don't, off-hand, remember how Kramdown interprets this stuff, I have to go look every time. I suspect it's 4-spaces-or-a-tab. It may be easier to change that line to like `foo<tab>bar` or something.

2021-11-23 20:53 UTC, ajaust commented
> I don't, off-hand, remember how Kramdown interprets this stuff, I have to go look every time. I suspect it's 4-spaces-or-a-tab. It may be easier to change that line to like `foo<tab>bar` or something.

I removed the offending line from the test since I already had a line with text in front of a hard tab. The main idea of line 5 was to test for illegal hard tabs at the beginning of a line.

Somewhat unrelated to this PR: 
I still wonder whether rule MD040 (Fenced code blocks should have a language specified) is always triggered if a code block uses hard tabs instead of spaces. To me it is not a fenced code block so I would have no idea how to specify the language identifier.

2021-11-23 20:53 UTC, ajaust commented on CHANGELOG.md
> +* Added option `:code_blocks` to rule MD010. If set to false, hard tabs in code blocks
Fixed.

2021-11-23 20:53 UTC, ajaust commented on docs/RULES.md
> +`code_blocks` parameter to false.
Fixed.

2021-11-23 20:53 UTC, ajaust commented on lib/mdl/rules.rb
> +    hard_tab_lines -= codeblock_lines unless params[:code_blocks]
Fixed.

2021-11-23 20:53 UTC, ajaust commented on test/rule_tests/hard_tabs_code_blocks_style.rb
> +rule 'MD010', :code_blocks => false
Fixed.

2021-11-23 20:54 UTC, ajaust commented on lib/mdl/rules.rb
> +  params :code_blocks => true
Fixed.

2021-11-23 20:54 UTC, ajaust commented on docs/RULES.md
> +Parameters: code_blocks (boolean; default true)
Fixed.

2021-11-23 20:55 UTC, ajaust commented
I changed the parameter name to `ignore_code_blocks` now and also its default value. The documentation has been changed accordingly as well.

2021-11-23 23:32 UTC, jaymzh approved these changes
Nice. Thanks.

Yeah, I agree that 040 seems to have a bug there.

2021-11-24 07:36 UTC, ajaust commented
I just signed-off my commits (don't we squash them later) and fixed the formatting error in the changelog.

2021-11-24 08:20 UTC, jaymzh commented
Yeah I do squash them, but the point of DCO is that you're certifying _that code_ is yours. So if there's 5 commits in the middle, there's no certification that you didn't just take that code from somewhere else. And I'd just be creating a lie in the squashed message. If you sign off on all your commits, then when I squash them and keep one of your DCOs, I'm not lying, or putting words in your mouth. And there's a good record that you told me you had the legal right to contribute the code, and thus I had reason to believe you had legal right to contribute the code. A little cumbersome (less so if you just get in the habit of always committing with `-s`), but less so than a CLA. :)

2021-11-24 09:08 UTC, ajaust commented
I understand. I will make sure to sign off all commits immediately the next time or at least before the pipeline runs.

2021-11-24 17:24 UTC, jaymzh commented
Thanks!

2021-11-24 17:24 UTC, merged