Add checkstyle format output
markdownlint/markdownlint pull request #441
Opened 2022-12-14 09:00 UTC by GWillmann

## Description
For some CI tools it is useful to output reports in checkstyle.

This PR adds the option `-C` (long format: `--checkstyle`) and the corresponding checkstyle output

## Related Issues
[Add checkstyle format](https://github.com/markdownlint/markdownlint/issues/440)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [x] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

2023-09-06 21:02 UTC, jaymzh requested changes
This is great! Few small tweaks, and it needs a rebase.

2023-09-06 21:02 UTC, jaymzh commented on lib/mdl.rb
> +              <error line="#{line}" severity="error" message="#{rule.description}" source="#{rule.docs_url}" />
this is error prone. How do you know there's not quotes in the line? This would break the XML parsing.

2023-09-06 21:02 UTC, jaymzh commented on lib/mdl.rb
> +      )
I'd prefer this be wrapped in an `if`. That way someone doesn't accidentally add something below it.

```suggestion
      if Config[:checkstyle]
        results << add_errors_to_file_name_xml_node(
          filename,
          results_by_filename.join,
        )
      end
```

2023-09-06 21:02 UTC, jaymzh commented on test/test_cli.rb
> +    assert_match(d.at('error')['source'], 'https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md002---first-header-should-be-a-top-level-header')
we just merged a serif formatter, which added test fixtures of the full output, I'd rather follow that pattern than this kind of parsing.

2023-09-27 07:21 UTC, GWillmann commented
Closing in favor the new `SARIF` format, thanks for the review!

2023-09-27 07:21 UTC, closed without merging

2023-11-12 10:24 UTC, oliv3r commented
@GWillmann would you mind considering not closing this request?

SARIF is currently only supported by github, [gitlab](https://gitlab.com/gitlab-org/gitlab/-/issues/345082) is working on SARIF support, but it's not there and may not be there for quite some time.

But even if SARIF support is added to gitlab, it would be part of their SAST support features, which means some representation options fall under the premium and ultimate tier, which is sad.

Supporting checkstyle, allows us to [translate it to junit](https://www.shellcheck.net/wiki//JUnit) which can be interpreted by gitlab.

2023-11-13 08:54 UTC, GWillmann commented
Reopening PR based on comment https://github.com/markdownlint/markdownlint/pull/441#issuecomment-1807083508

2023-11-13 08:55 UTC, GWillmann commented
Reopening PR based on comment https://github.com/markdownlint/markdownlint/pull/441#issuecomment-1807083508