Feat MD033 allowed elements
markdownlint/markdownlint pull request #450
Opened 2023-03-18 04:15 UTC by iafelix

## Description

To allow specific HTML elements, use the `allowed_elements` parameter.

That option is already available for Node.js

## Related Issues
Fix #118  #189 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [ ] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

2023-03-19 11:04 UTC, nbehrnd commented
@iafelix You are right to correct my error of `ammend` to `amend` (commit afd92a3).

When browsing through the commit history of changes you suggest, I notice the two first of three commits (afd92a3 `docs: fix typo on git option` and 30e6dff `docs: add allowed-elements parameter`) are not signed.  With the perspective of `CONTRIBUTION.md` (section contributions, 3.iv), only the most recent commit by you (748de0c `feat: add allowed-elements parameter`) in the sequence of events is "complete".  Because one commit builds on top of the other, can you modify your PR - each change by you is signed by you - please?

2023-03-19 11:13 UTC, nbehrnd commented
In your PR, the check list GitHub is asked to consider contains one empty line (`Added tests ...`), because it is irrelevant to the change suggested.  This is a situation similar to one when I filed a PR to markdownlint earlier; I removed this "empty" / irrelevant line in the PR.  As a result, the "traffic light" can switch to green without consideration of this point.

2023-03-20 05:34 UTC, jaymzh requested changes
The code looks good, but this needs some tests. You can find lots of examples of tests in the `test` directory.

Also, not all of your commits have sign-off on them, but they all need to.

2023-03-20 12:16 UTC, iafelix commented
@nbehrnd and @jaymzh signed off as requested.
@jaymzh added tests cases as requested.

2023-03-20 16:02 UTC, jaymzh requested changes
Test looks good, thanks.

You're still failing the DCO test (one of your commits lack's sign-off). Usually the easiest way to fix that is to rebase-and-squash them all (`git rebase -i upstream/main`, and then choose `s` for all commits but one, save/quit, then amend the resulting single commit to add as sign-off (`git commit -as`). You'll need to force-push your branch after that, the safest way to do so is `git push origin iafelix:feat-md033-allowed-elements --force-with-lease`

You can, instead, rewrite each of the old commits using the same general process (there's an option for rewrite instead of squash). You'll still need to force push though. But since we squash-merge in this repo, it's not really worth keeping all your separate commits.

2023-03-20 16:34 UTC, iafelix commented
@jaymzh thanks for guidance 🏅  
Hopefully I did it right this time 🙏

2023-03-20 16:49 UTC, jaymzh requested changes
The check is still failing, but looking at it, it's not because you don't have a sign-off, it's because it doesn't match the email address you're using in git:

```
748de0cae976e0eb2fb055e6c47608b67aaa05f1    Expected "Nelson Rodrigues Ferreira Junior <nelsonrf@kyndryl.com>", but got "iafelix <njr.iafelix@gmail.com>".
  7c1b0b86c5635b9d332239f49377a5f04a5d3f36    The sign-off is missing.
```
See logs here:
https://github.com/markdownlint/markdownlint/actions/runs/4470517845/jobs/7854672669?pr=450

2023-03-20 17:16 UTC, jaymzh commented
>   748de0cae976e0eb2fb055e6c47608b67aaa05f1    Expected "Nelson Rodrigues Ferreira Junior <nelsonrf@kyndryl.com>", but got "iafelix <njr.iafelix@gmail.com>".

2023-03-20 20:30 UTC, jaymzh commented
See logs... You now have unit tests failing and no sign offs

2023-03-20 20:40 UTC, iafelix commented
Sorry for all the mess... this is my very first time working with signed commits

2023-03-20 20:44 UTC, jaymzh commented
No worries. I've updated the settings for the repo so they SHOULD start auto-running the checks everytime you push now. I'll leave you to it until all the tests pass. :)

2023-03-20 20:45 UTC, iafelix commented
There is another issue regarding another rule, may I fix that too?

2023-03-20 20:51 UTC, jaymzh commented
No, it's not, it's your test, ` TestRules#test_inline_html`. You added text to the test file and you're triggering another rule.

2023-03-20 21:11 UTC, iafelix commented
Sorry, I meant this warning:
```text
MD013 warning: Parameter :code_blocks is deprecated.
  Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
```

2023-03-20 21:46 UTC, jaymzh commented
That's a test testing for that warning, it's not failing ;)

Looks like my attempt to get the workflows to autorun aren't working - I set to to only require approval for new contributors who are _also_ new to GH, which I guess you fall into. No worries I'll just keep this window open and hit the button

2023-03-20 22:00 UTC, iafelix commented
Maybe you could try something like:
```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened]
```

But I don't know if worth it as we are almost done (crossed fingers) lol

2023-03-20 22:24 UTC, jaymzh commented
> Maybe you could try something like:

No, it's already triggering them. It just requires approval in case you've add nefarious code to the codebase to try to break out of the container via the tests.

2023-03-21 14:53 UTC, iafelix commented
@jaymzh ping

2023-03-21 16:02 UTC, jaymzh commented
button clicked, sorry :)

2023-03-21 16:04 UTC, jaymzh approved these changes

2023-03-21 16:04 UTC, jaymzh commented
Nice, thanks!

2023-03-21 16:05 UTC, merged

2023-03-21 16:48 UTC, iafelix commented
Thanks a lot! Just one more thing...
[When the code will be available in a release of Markdownlint](https://github.com/markdownlint/markdownlint/blob/main/CONTRIBUTING.md#release-cycles) link on [CONTRIBUTING.md](CONTRIBUTING.md) is broken/missing, could you please provide an ETA?

2023-03-21 18:35 UTC, nbehrnd commented
@iafelix By the landing page, to clone from GitHub and run a `rake install` always offers the most recent version of the program.  Next is the release on rubygems, and latest in a Linux repository. (The one for [Debian](https://tracker.debian.org/pkg/ruby-mdl) and its relatives for example will not be updated until `Debian 12/bookworm` (currently frozen branch `testing`, [schedule](https://wiki.debian.org/DebianBookworm)) transitioned into branch `stable` - which perhaps happens in Q3/2023).

2023-03-21 18:50 UTC, jaymzh commented
We did a release recently, and this is the first code change since then, so I don't know I'll do a formal release just yet. I usually try to wait until there's a few features/fixes in the pipeline before cutting a release.